name: SAC
main: DarkWav\SAC\SAC
version: 3.3.0
load: STARTUP
enable: STARTUP
author: DarkWav
api: [3.0.0-ALPHA9,3.0.0-ALPHA10,3.0.0-ALPHA11,3.0.0-ALPHA12,3.0.0-ALPHA13,3.0.0-ALPHA14,3.0.0-ALPHA15,3.0.0-ALPHA16,3.0.0-ALPHA17,3.0.0-ALPHA18,3.0.0]
commands:
      shadowanticheat:
           description: Shows ShadowAntiCheat version
           aliases: ["ShadowAntiCheat","AntiCheat","SAC"]
      sac:
           description: Shows ShadowAntiCheat version
           aliases: ["ShadowAntiCheat","AntiCheat","SAC"]
permissions:
    sac:
        description: "Allows to use all sac features."
        default: false
        children:
            sac.admin:
                description: "Get notified when someone is hacking."
                default: op
            sac.fly:
                description: "A permission."
                default: false
            sac.glide:
                description: "A permission."
                default: false
            sac.speed:
                description: "A permission."
                default: false
            sac.noclip:
                description: "A permission."
                default: false
            sac.reach:
                description: "A permission."
                default: false
            sac.instantkill:
                description: "A permission."
                default: false
            sac.killaura:
                description: "A permission."
                default: false
            sac.regen:
                description: "A permission."
                default: false