name: VAC
main: DarkWav\VAC\VAC
version: 3.0.0
load: STARTUP
enable: STARTUP
author: DarkWav
api: [2.0.0,1.0.0]
commands:
      voidanticheat:
           description: Shows AntiCheat version
           aliases: ["VoidAntiCheat","AntiCheat","VAC"]
      vac:
           description: Shows AntiCheat version
           aliases: ["VoidAntiCheat","AntiCheat","VAC"]
permissions:
    vac:
        description: "Allows to use all AntiCheat features."
children:
    vac.op:
        description: "A permission."
